install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev qt4-qmake
  - wget https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz --no-check-certificate
  - tar xzvf mbedtls-2.2.1-apache.tgz
  - cd mbedtls-2.2.1/
  - make
  - sudo make install

script:
  - cd ..
  - qmake -project
  - qmake pb173-krypto.pro
  - make
