install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install qtbase-opensource-src
  - sudo apt-get install g++-4.8
  - wget https://tls.mbed.org/download/mbedtls-2.2.1-apache.tgz --no-check-certificate
  - tar xzvf mbedtls-2.2.1-apache.tgz
  - cd mbedtls-2.2.1/
  - make
  - sudo make install

script:
  - cd ..
  - qmake pb173-krypto.pro
  - make
